"""Init1

Revision ID: 47ae1c1876a7
Revises: f8e75ada94fc
Create Date: 2025-01-06 20:26:14.416586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ae1c1876a7'
down_revision: Union[str, None] = 'f8e75ada94fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
